site_name: MatrixSku-Blog
site_description: 晖-随记
site_url: https://www.matrixsku.com/

theme:
  name: material
  language: zh
  features:
    - navigation.instant #即时加载
    - navigation.instant.progress #示在页面顶部-进度指示器
    - navigation.tracking #锚点追踪 地址栏中的 URL 会自动更新为内容列表中突出显示的活动锚点
    - navigation.tabs #导航选项卡
    - navigation.tabs.sticky #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.expand #导航扩展 启用扩展后，左侧边栏将默认展开所有可折叠的小节
    - navigation.sections #两个功能标志navigation.tabs和可以相互组合。如果两个功能标志都启用，navigation.sections部分为级别 2 渲染导航项目。
    - toc.follow #当启用目录的锚点跟随时，侧边栏会自动滚动，以便活动锚点始终可见
    - toc.integrate  #启用目录的导航集成后，它始终呈现为左侧导航侧边栏的一部分
    - navigation.top  #当用户向下滚动后开始再次向上滚动时，可以显示返回顶部按钮
  palette: #调色板
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 自动模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 太阳神
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 月神
  logo: assets/logo.png #徽标可以更改为位于文件夹中的用户提供的图像
  favicon: images/favicon.png #可以将图标更改为指向用户提供的图像的路径，该图像必须位于该docs文件夹中

plugins:
  - blog:
      authors_file: "{blog}/.authors.yml" #使用此设置可以更改帖子作者信息所在的文件路径。通常不需要更改此设置 以下占位符可用：blog-blog目录
nav:
  - 博客: index.md
  - 云原生:
    - CNI: cni.md
    - CRI: cri.md
    - SCI: csi.md

