site_name: MatrixSku-Blog
theme:
  name: material
  language: zh
  features:
    - navigation.instant #即时加载
    - navigation.instant.progress #示在页面顶部-进度指示器
    - navigation.tracking #锚点追踪 地址栏中的 URL 会自动更新为内容列表中突出显示的活动锚点
    - navigation.tabs #导航选项卡
    - navigation.tabs.sticky #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.expand #导航扩展 启用扩展后，左侧边栏将默认展开所有可折叠的小节
    - toc.follow #当启用目录的锚点跟随时，侧边栏会自动滚动，以便活动锚点始终可见
    - toc.integrate  #启用目录的导航集成后，它始终呈现为左侧导航侧边栏的一部分
    - navigation.top  #当用户向下滚动后开始再次向上滚动时，可以显示返回顶部按钮
plugins:
  - blog:
      authors_file: "{blog}/.authors.yml" #使用此设置可以更改帖子作者信息所在的文件路径。通常不需要更改此设置 以下占位符可用：blog-blog目录
nav:
  - 主页: index.md
  - 分类:
    - 标题1: test.md
    - 标题2: test2.md
  - Blog:
    - blog/index.md
